version: 0.2

phases:
  install:
    commands:
    - echo Entered the install phase..
    - sudo apt update -y
    - echo Downloading Terraform...
    - wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - sudo apt update
    - echo Install Terraform...
    - sudo apt install terraform -y
    - terraform -version
    - terraform init
    - terraform import aws_iam_role.iam_for_codebuild iam_for_codebuild
    - terraform import aws_iam_role_policy.codebuild_policy iam_for_codebuild:uchicago_codebuild_policy
    - terraform import aws_iam_role.iam_for_codepipeline iam_for_codepipeline
    - terraform import aws_iam_role_policy.codepipeline_policy iam_for_codepipeline:uchicago_pipeline_policy
    - terraform import aws_codebuild_project.chicago_build uni-chicago
    - terraform import aws_codepipeline.codepipeline uni-chicago-pipeline
    - terraform import aws_s3_bucket.codepipeline_bucket unichicago-codepipeline-bucket
    - terraform plan
  build:
    commands:
    - echo Entered the build phase...