version: 0.2

phases:
  install:
    commands:
    - sudo apt update
    - echo Downloading Terraform...
    - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo Install Terraform...
    - sudo apt install terraform
    - terraform -version
